- id: sump_pump_automation         
  alias: Sump Water Detected
  trigger:
  - platform: state
    entity_id: binary_sensor.sump_water_detect
    to: 'on'
    for:
      seconds: 15
  action:
    - service: notify.PUSHBULLET
      data_template:
        title: 'HASS - DANGER: Sump Pump Detected Water @  "{{now().strftime("%H:%M:%S %m-%d")}}"'
        message: 'HASS - Water was detected in the sump pump room at "{{now().strftime("%H:%M:%S %Y-%m-%d")}}". The distance is {{ states.sensor.sump_distance.state }} cm'
    - service: homeassistant.turn_on
      entity_id: script.sump_water_notify_rate_limit

- id: marisa_notification    
  alias: Notify Marisa at Home
  trigger: 
  - platform: state
    entity_id: !secret google_maps_tracker_marisa
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: !secret google_maps_tracker_nuno
    state: 'not_home'
  action:
    - service: notify.telegram
      data:
        title: Send an images
        message: That's an example that sends an image.
        data:
          photo:
            - url: http://192.168.1.67:99/snapshot.cgi
              username: !secret user1
              password: !secret password1
#            - file: /tmp/picture.jpg
#              caption: Picture Title xy
#            - url: http://somebla.ie/video.png
#             caption: I.e. for a Title
#    - service: notify.telegram
#      data:
#        title: Send a video
#        message: That's an example that sends a video.
#        data:
#          video:
#            - url: http://192.168.1.67:99/videostream.cgi?user=xxx&pwd=xxx&resolution=32&rate=0
#              username: !secret user1
#              password: !secret password1
#    - service: notify.telegram
#      data: 
#        message: 'Marisa is at home.'

#- id: arduino_is_dead
#  alias: Notify if Arduino sensor state unchanged
#  trigger: 
#    platform: template
#    value_template: "{% if as_timestamp(states.sensor.date__time.last_updated) - as_timestamp(states.sensor.sump_distance.last_updated) > 5*60 %}true{% endif %}"
#  action:
#    service: notify.PUSHBULLET
#    data: 
#      message: 'Arduino sensor state unchanged in the last 5 minutes.'

- id: arduino_is_dead
  alias: Notify if Arduino sensor state unchanged
  trigger:
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.sensor.sump_distance.last_updated)) | int > 300 }}'
  action:
    service: notify.PUSHBULLET
    data: 
      message: 'Arduino sensor state unchanged in the last 5 minutes.'

#- alias: 'Sump Water Detected'
#  trigger:
#    platform: state
#    entity_id: binary_sensor.sump_water_detect
#    state: 'on'
#    for:
#      seconds: 15
#  action:
#    - service: notify.PUSHBULLET
#      data_template:
#        title: 'HASS - DANGER: Sump Pump Detected Water @  "{{now().strftime("%H:%M:%S %m-%d")}}"'
#        message: 'HASS - Water was detected in the sump pump room at "{{now().strftime("%H:%M:%S %Y-%m-%d")}}". The distante is {{ states.sensor.sump_water_detect.state }} cm'
#    - service: homeassistant.turn_on
#      entity_id: script.sump_water_notify_rate_limit
