homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

############## Services 
mqtt: 
  broker: 192.168.1.114
  discovery: True

notify:
  - name: PUSHBULLET
    platform: pushbullet
    api_key: !secret pushbullet_key
  - name: TELEGRAM
    platform: telegram
    chat_id: !secret telegram_chatid


    # Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chatid

sensor:
  - platform: yr
  - platform: mqtt
    state_topic: "basement/sump"
    unit_of_measurement: "cm"
    name: "Sump Distance"
    value_template: '{{ value_json.current }}'

  - platform: mqtt
    state_topic: "basement/sump"
    name: "Alarm Heartbeat"
    value_template: '{{ as_timestamp(now()) }}'
    qos: 0

  - platform: mqtt
    state_topic: "basement/sump"
    name: "Sump Water Lvl"
    value_template: >
        {% if value_json.current | int > 150 %}
          0
        {% else %}
          {{ (value_json.current | int) }}
        {% endif %}
    unit_of_measurement: "cm"

  - platform: statistics
    name: "Sump Water Level Stats"
    entity_id: sensor.sump_distance
    sampling_size: 30

  - platform: template
    sensors:
      sump_water_level:
        value_template: "{{ states.sensor.sump_water_level_stats_mean.attributes.median | int }}"
        friendly_name: "Water Level"
        unit_of_measurement: "cm"

  - platform: mqtt
    state_topic: "tele/hygrometer-DAA0/TEMP"
    unit_of_measurement: "ºC"
    name: "Temperature Monitor"
    value_template: '{{ value_json }}' 
  - platform: mqtt
    state_topic: "tele/hygrometer-DAA0/HUMI"
    unit_of_measurement: "%"
    name: "Humidity Monitor"
    value_template: '{{ value_json }}' 

  - platform: mitemp_bt
    name: "Hall Room Temp"
    mac: '4C:65:A8:D2:DA:A0'
    force_update: false
    median: 5
    monitored_conditions:
      - temperature
      - humidity
      - battery

binary_sensor:
#  - platform: threshold
#    name: "Sump Status"
#    sensor_class: power
#    threshold: 2
#    type: upper
#    entity_id: sensor.sump_current
  - platform: mqtt
    state_topic: "basement/sump"
    name: Sump Water Tracker
    sensor_class: moisture
    payload_on: "1"
    payload_off: "0"
    value_template: '{{ value_json.water }}'

camera:
  - platform: mjpeg
    name: Outside Camera
    still_image_url: !secret still_image_url
    mjpeg_url: !secret mjpeg_url
#  - platform: generic
#    name: Hall Camera
#    still_image_url: http://192.168.1.101/tmpfs/auto.jpg
#    username: !secret user1
#    password: !secret password1
  - platform: ffmpeg
    name: Basement Camera
    input: rtsp://192.168.1.84:554/onvif1
    username: !secret user1
    password: !secret password1
    authentication: basic
  - platform: ffmpeg
    name: Hall Camera
    input: !secret camera_input
    username: !secret user1
    password: !secret password1
    authentication: basic

xiaomi_aqara:
  gateways:
    - host: 192.168.1.117 
      mac: !secret xiaomi_gw_mac
      key: !secret xiaomi_gw_key

device_tracker:
  - platform: thomson
    host: 192.168.1.254
    username: !secret thomson_user
    password: !secret thomson_passwd
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False
#  - platform: nmap_tracker
#    home_interval: 10
#    hosts: 
#      - 192.168.1.0/24
#      - 192.168.1.104
#    exclude:
#      - 192.168.1.114
#     
#    interval_seconds: 30
  - platform: ping
    hosts: 
#      nuno_ping: 192.168.1.99
#      marisa_ping: 192.168.1.104
      ArduinoBomba: 192.168.1.116
  - platform: google_maps
    username: !secret google_user_casa
    password: !secret google_passwd_casa
    new_device_defaults:
      track_new_devices: true
  - platform: bluetooth_tracker

#STB MEO
media_player:
  - platform: mediaroom
    name: "Mediaroom STB"

#logger:
#  default: warning

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
